### ISSUE TITLE
Getting error for TokenType because it is not clearly mentioned how to get the token with example links

### ISSUE THREAD

**Issue by shariZee** [AgoraIO-Community/agora-token-service#22]
@maxxfrazer @digitallysavvy @EkaanshArora @hxingpax @Mupati
I tried this: 
`https://nikah----match.herokuapp.com/rtc/:test/:publisher/:userAccount/:0/?expireTime`

and got:
` {"error":"Error Generating RTC token - failed to generate RTC token for Unknown Tokentype: :userAccount","status":400}`

Also tried: 
`https://nikah----match.herokuapp.com/rtc/:test/:publisher/:uid/:0/?expireTime`

and got: 
` {"error":"Error Generating RTC token - failed to generate RTC token for Unknown Tokentype: :uid","status":400}`

You should at least have some example links in the Readme file.

**Comment by maxxfrazer** [comment]
try instead:

https://nikah----match.herokuapp.com/rtc/test/publisher/0

**Comment by shariZee** [comment]
Thanks a lot. found the example links in the Guide.md. But I think these example links should be there in the Readme file.

Found these links: 
```
http://localhost:8080/rtc/testing/publisher/userAccount/1234/
http://localhost:8080/rtc/testing/publisher/uid/1234/
```

**Comment by maxxfrazer** [comment]
When we add the ":variable" syntax in a URL example, that means replace it with the value.

This is in the readme:
`/rtc/:channelName/:role/:tokentype/:uid`

**Comment by shariZee** [comment]
@maxxfrazer 
Yes, sorry about that. didn't know that. 
Another question: I just copied: https://nikah----match.herokuapp.com as the tokenUrl in the AgoraConnectionData constructor as given here: 

```
final AgoraClient client = AgoraClient(
    agoraConnectionData: AgoraConnectionData(
      appId: "", //omitted for security reasons
      tokenUrl: "https://nikah----match.herokuapp.com/rtc",
      // tokenUrl: "https://nikah--match.herokuapp.com/access_token?",
      channelName: channelName,
      uid: 0,
    ),
    enabledPermission: [
      Permission.camera,
      Permission.microphone,
    ],
  );
//the commented line was my previous NodeJS server with old code and different parameters. 
//that's why I hosted this one now as the link in the original AgoraConnectionData class referred to this server.
```

But still, I get:

```
I/flutter (15044): Not Found
I/flutter (15044): Failed to generate the token: 404

```

What is the reason? I mean how do I put it there? because it should be working with this link as that is the original server link.

**Comment by maxxfrazer** [comment]
you haven't added the link you said in the message, you've appended "/rtc" to it. Remove that and it should be fine.

The token server handles rtc and rtm tokens

**Comment by waqadArshad** [comment]
No, actually I did try that too. and it still doesn't work. Please see the whole details of the BUG you just mentioned here.

Like:

What else I tried:
```

https://nikah----match.herokuapp.com/rtc

https://nikah----match.herokuapp.com/rtc/test/publisher/uid/0

https://nikah----match.herokuapp.com/rtc/:channelName/publisher/uid/0

https://nikah----match.herokuapp.com/rtc/$channelName/publisher/uid/0

https://nikah----match.herokuapp.com/rtc/:channelName/:role/:tokentype/:uid
```

quoted from: `https://github.com/AgoraIO-Community/Flutter-UIKit/issues/73`

**Comment by maxxfrazer** [comment]
Doing some cleaning, as this was closed in https://github.com/AgoraIO-Community/Flutter-UIKit/issues/73
